server:
  port: 8100

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://eureka:8761/eureka

security:
  jwt:
    secret: ${GATEWAY_JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 30000
        response-timeout: 10s

      discovery:
        locator:
          enabled: true

      routes:
      - id: userService
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        filters:
          - RemoveRequestHeader=Authorization
          - RemoveRequestHeader=Cookie
          - RemoveRequestHeader=Set-Cookie

      - id: bannerService
        uri: lb://BANNER-SERVICE
        predicates:
        - Path=/banner/**
        filters:
        - StripPrefix=1
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        - TokenValidationFilter

      - id: minecraftService
        uri: lb://MC-SERVICE
        predicates:
        - Path=/mc/**
        filters:
        - StripPrefix=1
        - RemoveRequestHeader=Authorization
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie